### ISSUE TITLE
some questions about border treatment

### ISSUE THREAD

**Issue by Karbo123** [Trinkle23897/Fast-Poisson-Image-Editing#1]
First of all, I highly appreciate this great work, which implements lots of methods to perform poisson image editing with different backends, where I really value the promising implementations of CUDA and Taichi which enable me to use poisson image editing during my deep network training although it isn't differentiate. Although it seems perfect right now, I may have a small issue about the special treatment of image boundary, because it's likely that the blending result is less satisfactory if the mask touches the image border.

https://github.com/Trinkle23897/Fast-Poisson-Image-Editing/blob/d605cf90542ddac7cd47ae830f713510f1a5d935/fpie/process.py#L183-L187

Since my mask will touch the image border, so the codes above will forcely set the mask value to 0 (instead of keeping the original 255). I think this is because the current implementation don't give a special treatment to this case, and therefore if the target image have wrong values inside the masked region (e.g. all zeros inside the mask) and we use `gradient="src"`, the filled values will definitely affect the blending results because the filled values are also involved in the boundary constraints (some mask values are set to zero, see above).

I wonder to know, if I want to address this, what should I do and modify the codes so as to keep the changes minimum? 

Thank you very much!

**Comment by Trinkle23897** [comment]
Could you please give me a command to reproduce what you said above?

```bash
fpie -s test7_src.jpg -t test7_tgt.jpg -o result7.jpg -h1 50 -w1 30 -n 5000 -g src
```

This command will have `mask == 255` with `mask.shape == src.shape`, but I don't see any issue with the resulted image.

**Comment by Karbo123** [comment]
Sure, you can try this example:
```bash
fpie -s src.png -t tar_masked.png -m mask.png -o out.png -g src
```
where the images can be downloaded from [mask.png](https://upload.cc/i1/2022/07/17/KvpP7w.png), [tar_masked.png](https://upload.cc/i1/2022/07/17/OmRH1b.png) and [src.png](https://upload.cc/i1/2022/07/17/Z9hP3R.png).

And also, I found a simple solution to this problem, I'm not sure if it's the best solution, it's to copy the border before zeroing out the mask's border.
```python
    # deal with border (NOTE: we newly add this four lines to codes)
    tgt[0, mask[0]==1] = src[0, mask[0]==1]
    tgt[-1, mask[-1]==1] = src[-1, mask[-1]==1]
    tgt[mask[:, 0]==1, 0] = src[mask[:, 0]==1, 0]
    tgt[mask[:, -1]==1, -1] = src[mask[:, -1]==1, -1]

    # zero-out edge
    mask[0] = 0
    mask[-1] = 0
    mask[:, 0] = 0
    mask[:, -1] = 0
```

**Comment by Trinkle23897** [comment]
Sorry for the late reply. Sounds good to me, but you should handle the corner case as well. I tested locally and it seems like it cannot run the example successfully:
```bash
$ fpie -s test2_src.png -m test2_mask.png -t test2_tgt.png -o result2.jpg -h1 130 -w1 130 -n 5000 -g src --method grid
Traceback (most recent call last):
  File "/Users/jiayi/.virtualenvs/bin/fpie", line 8, in <module>
    sys.exit(main())
  File "/Users/jiayi/.virtualenvs/lib/python3.9/site-packages/fpie/cli.py", line 37, in main
    n = proc.reset(src, mask, tgt, (args.h0, args.w0), (args.h1, args.w1))
  File "/Users/jiayi/.virtualenvs/lib/python3.9/site-packages/fpie/process.py", line 309, in reset
    tgt[0, mask[0]==1] = src[0, mask[0]==1]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 418 but corresponding boolean dimension is 180
```

Anyway, the `zero-out edge` method is the simplest way that can cover most of the input with no error, so feel free to change this error-handling part.
