### ISSUE TITLE
 Legacy-install-failure installing fpie package #64 

### ISSUE THREAD

**Issue by toonpeters** [Trinkle23897/Fast-Poisson-Image-Editing#4]
I had some problems with installing the fpie package. I already updated the wheel and installed the cmake package manually.

![image](https://user-images.githubusercontent.com/74351240/195310219-a86410d7-9c67-474a-a3c7-a3d53480ec26.png)

- OS: Ubuntu debian 18.04.6 LTS
- CUDA 11.4
- Nvidia RTX A5000 and Nvidia GeForce RTX 3090
- Browser firefox

**Comment by Trinkle23897** [comment]
What’s the output of `camel —version`?

**Comment by urbanscribe** [comment]
cmake version 3.22.1
fails

**Comment by Trinkle23897** [comment]
fixed, please upgrade to version 0.2.4
